# https://github.com/dessant/label-actions

issues:
  actions:
    done:
      comment: >
        Issue resolved. Im closing this down.
      close: true
    duplicate:
      comment: >
        Issue is marked as __duplicate__.
      close: true
