on:
  issue_comment:
    types: [ created ]

jobs:
  issue-commented:
    name: Self assign issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comment_content = context.payload.comment.body

            if (comment_content.includes(`@I'm working on it`)
                || comment_content.includes(`@I'm on it`)
                || comment_content.includes(`@I will do it`)
            ){
              github.issues.addAssignees({
                            issue_number: context.payload.issue.number,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            assignees: context.payload.comment.user.login
                          })
            }

