on:
  issue_comment:
    types: [ created ]

jobs:
  issue-commented:
    name: Self assign issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(JSON.stringify(context.payload.comment, null, 2))
            const comment = github.issues.getComment({
                            owner: context.repo.owner,
                            repo: context.repo.owner,
                            comment_id: context.payload.comment.id
            })
            if (x.includes(`@I'm working on it`)
                || x.includes(`@I'm on it`)
                || x.includes(`@I will do it`)
            ){
              github.issues.addAssignees({
                            issue_number: context.payload.issue.number,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            assignees: context.payload.comment.user.login
                          })
            }

