# Add to reviewers field if you want to review :)

on:
  issues:
    types: [ labeled ]

jobs:
  complicated_label_scheme:
    name: request
    runs-on: ubuntu-latest
    steps:
      - name: remove new label
        if: |
          contains(github.event.issue.labels.*.name, 'new')
          && (
          contains(github.event.issue.labels.*.name, 'Status: maybe later')
          || contains(github.event.issue.labels.*.name, 'Status: scheduling')
          || contains(github.event.issue.labels.*.name, 'Status: in progress')
          || contains(github.event.issue.labels.*.name, 'Status: done')
          || contains(github.event.issue.labels.*.name, 'Status: wontfix')
          )
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/new


      - name: request reviewer
        if: |
          contains(github.event.issue.labels.*.name, 'Status: waiting for review')
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number
          }}/requested_reviewers \
            -d '{"reviewers":["alitonia", "leehoang2000"]}'
