# Add to reviewers field if you want to review :)

on:
  issues:
    types: [ labeled ]

jobs:
  complicated_label_scheme:
    name: request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // request code reviews
            const labels = context.payload.issues.labels || []
            if(labels.filter(x => x.name === 'Status: waiting for review').length!==0){
              github.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: ['alitonia', 'leehoang2000']
            })
            }

            // close finished issues
            if(labels.filter(x => x.name === 'done').length!==0){
                          github.issues.update({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.payload.issue.number,
                            state: 'closed'
                        })
                        }

