# Add to reviewers field if you want to review :)

on:
  issues:
    types: [ labeled ]

jobs:
  complicated_label_scheme:
    name: request
    runs-on: ubuntu-latest
    steps:
      - name: request reviewer if match
        if: "contains(github.event.pull_request.labels.*.name, 'Status: waiting for review')"
        run: |
          echo 'Working as intended'

      - name: end
        run: |
          echo hello
