on:
  issues:
    types: [ opened ]

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add new label
        run: |
          curl --request POST \
                    --url 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number
          }}/labels' \
                    --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
                    --header 'Accept: application/vnd.github.v3+json' \
                    --data-raw '{"labels":["new"]}'
