# Add to reviewers field if you want to review :)

on:
  issues:
    types: [ labeled ]

jobs:
  complicated_label_scheme:
    name: request
    runs-on: ubuntu-latest
    steps:
      - name: request reviewer
        if: |
          contains(github.event.issue.labels.*.name, 'Status: waiting for review')
        run: |
          echo hello
