on:
  issues:
    types: [ assigned ]

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: remove unnecessary label new
        if: |
          contains(github.event.issue.labels.*.name, 'new')
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number}}/labels/new

      - name: remove unnecessary label help wanted
        if: |
          contains(github.event.issue.labels.*.name, 'help wanted')
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number
          }}/labels/help+wanted

      - name: remove unnecessary label wontfix
        if: |
          contains(github.event.issue.labels.*.name, 'wontfix')
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number
          }}/labels/wontfix


